language: java

if: tag IS blank

install:
- mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -V -B

script:
- mvn test -B

  #before_deploy:
  #- export RELEASE_REVISION=".$TRAVIS_BUILD_NUMBER"
  #- export RELEASE_VERSION=$(mvn org.codehaus.mojo:exec-maven-plugin:1.3.1:exec -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive -B | sed -e "s/-SNAPSHOT/$RELEASE_REVISION/")
  #- echo "Releasing [$RELEASE_VERSION]"
  #- openssl aes-256-cbc -K $encrypted_8d05669b0f5a_key -iv $encrypted_8d05669b0f5a_iv -in .travis.codesigning.asc.enc -out .travis.codesigning.asc -d
  #- gpg --fast-import .travis.codesigning.asc
  #- travis_wait mvn deploy -P release -DskipTests=true --settings .travis.settings.xml -Drevision="$RELEASE_REVISION" -B
  #- git config --local user.name "Lucas Theisen"
  #- git config --local user.email "lucastheisen@pastdev.com"
  #- git tag -a -m "v$RELEASE_VERSION" $RELEASE_VERSION
  #
  #deploy:
  #  provider: releases
  #  api_key:
  #    secure: "AwXte78wm1wYJ2i8kUDGl7g+xy5s2xx19Xp4O7skRUJ1S272nEuAY8fpoeJZRScYeNRISjnfWeCZORtVlQaALjwBmJtI0QJSyRloIAYAD6Uvhr1/xgL67ICOkTikLJNWF1wnoGfoazQr+peFRb4z8YfgAsw3RcR0I70QiS6yZOrgqTBaRRupavA57Be2RALkU1Mp5z25dE2LPJMAvlFBiNO8LRO5zZ+8eibhLPiEybh9H5kuLOhgbHj9NpujCXaPmRy4T7EzMiTWAE0E1I27u8KbjW0sZijbBEWe0AWfLKy8Tv0RaZp0lmPa45MPemqvpjfUP0xqgSOzR6yIjvXcVBhoIOCTLLvsVPMdGNp+hkIk2WK83xnAcjMygDG5rSVMhXGt22IbcppCORyAIc3ncQo0oUgrB5bmSODVEWhBUO2D7OTFPOLjI7RUxSX0ITh0tV3CxUaRt9EjK4iUbgnAuHxMBJtL80yCzMFPeyom5md/8hXcMhf1JgGvRAMUyyeOKy+m4ppPPcLGCjlzQNNNB4sidyL11uM12TtUPfh3U8xjx0VOXJDvQ9czlo0zZuzoLdTAaZYc/PT3krJxve7NGmvyDmUpp/dZ8PlwOP0g6cm6qPEq3kcAjO/XsP0M6zZaaM7b3d9aDdrE8hZ1r8iLjS57jqsMaZSPsg54yRNJhNM="
  #  on:
  #    branch: master
  #    tags: false

# In order:
# travis encrypt MAVEN_REPO_PASSWORD=\"REDACTED\"
# travis encrypt MAVEN_REPO_USERNAME=\"REDACTED\"
# travis encrypt MAVEN_GPG_KEYNAME=\"REDACTED\"
# travis encrypt MAVEN_GPG_PASSPHRASE=\"REDACTED\"
env:
  global:
    - secure: "POh6DD8DyOjxr3q1w1MFWB4VfZuygvkdMEqJMffEiGBeoIQiyWiJLgRNhcykcHvOYhzBkYwWskJBdUdxSpiJGswC5vOXYWdgMwwKoBV8ejsMbFNGy4baHMfp4N4qZ06I8a6AxMu6JfEW9LN5Iv5OnbRKWFTMj8vWoy5tOuzsauG9i4LgSYOckz8AxAUaalVqsr5DAw4C49YbZbloaoDpo7J3yTdzoGjZntRe0z70jMY4SwSibH9TYR+qXRa0SCArNERLLUkK8ZMISv+cWFC6Non/zZLYWNHCXIo7DMDfYbXrVFanghpa4JSPXzYO8ez7wmD8bRhGIZommrFfHTeueqaoRMK8CG+JkB18KXr0yfsIQbtc84g797oRXRoeIDtOkqGgxIW+xvoXaXdHXVuZsfGJ/unchjtUdsQjkQmcOralRLbpQdfzeTZY4ePdgyqMyCaWOV4yFE+b0t+s+G/V/Whbiq5CbwDZi/oL3YLcfIpHeU42i4OS8PdLSnEffbBxhsBbhwqff8HhUO0qshyOzSMmW6BAIsmecPpMA7coKyPQOZv+6AwlrLTpl4jg8W8aszODFd5w2y+rVCx//RLdwsHOOn9P67g7NCR1GVADgwanJ5tF98HTxSXoAxxZeC09MQyni6MHo3z+WQ7a7p2jn6xj4keW0rx4Q9Z2IDLqmog="
    - secure: "EAJQckdW7/fQ55NTyy+A9VGtv6ChBm7oX3sMrSQv7U4nrG3TtfMR3YOYWVf0lCYpUykzX8CDt8ZCGfWqQuCxsdbw0vy3PANHNmKw40Nj6TlcM1yF1W5Y5wSv/1aP/VmdtnI7uH9cApYDyMR5HePHxfQ/rkBRmcVq2mqglJ0hDoM1Sy7TM8j2SUQgtcvHS14iLmr200UGSpRJ+sdHqu6nMJifAF3I6xOYS+cRji86StfcYsg7a6mK7C0wOXIqZolSlJvPAARgRVXUIduzYdDvYFiVSJ0DVA0KKSzeYcwn6Mk4leqzowexMl9pM5BA1ODkyaVrIkRMoVGqg9nEl5p3NQrKNm+BrEhtv81KcSENGKQwyPz00Yryq/27soziNllukSppX0ISwWfAHH/hTRjmhnmsyLvMORYlaAARLvbJASxfa2cenjuY04kHLzE1v4y4mvYTl2FKrSRLN1hDkfFlGj0pVZBAasDpKRnvkgdjR8LM/eXnpUdXdvAV8PM9QqTDOyDVYg97A/Ad8+HTLaQsDe5QWpHllgykrY59NFImHO67sYRCCKBsZ2Airz6C1KGqf8geaJOGnL8hvLn6cNZuCfh57/ocLwBvSeIr7RJ63sd2mcIGeEXOnZcgUlG7Fj+u+S6sn4kyDuZCmwJcTtkGBhpkKRE7FOg9X3p8JR0jZoY="
    - secure: "Sg3QR2x/vR/7YRrLwh4V+ecuDPt4Gd/+Cvz8ElbnUbX0akLJ3uyfjN44VcRcogog0sUhKttSrcOeY2696lmSchf5zRq6BIL+wvLFLWdIzJ0E/Cq8LT4JaFMRugcbh5yPecclqT80CaUVNAQdnp6K98b9nkVCDvyO1HkYmo3foT87xjQ89Duk3WKtEyK7c3RbvtDWTeskiRmomdDqG/eQ/aH5z/ABj9naM7pJjHbi1hKeK5RpZMICiOUdJw2gC9UZQQ8rnB7xhyimU+8Dg+kl8XHAYoK3pQEpHht2oJtySMONMb9pbIsHNRAEQu5AYPCAqDBdsRy844rJYgG8AnTrppFkiLnLpNFHPG+rDZUIM+mNMYtG5SBRyRJFCwEBFEpiZP2wEj57v7LvgTqFbZJJwcJ50jIJgeBBj1d8L33ers7x29n3nmTSLFdsdbN0RUXx+jQkEM7/f2WezbcYyw3sMKBxW5E+onwNyf7mDblj5tmqXpkgT+5QF67QmCn8sdGWqVPJKyNNb/wj4fLII/zxPucEOqZjKWbU+ALiappkMu93sTf6itm/wotrI+gAF8PVeRbVgYjzy6t0khhknq5zJQBQeolRF44isikmgHyUI0ZKPQn+KwcX/gjBbc5QJpvRGJqRNr56ux8vR5o8cATevYJfeHFEtU2u27aQPZH8Csw="
    - secure: "pQToZH2mNEJ/R6pAFaYJN+FmXp21kxVBFMkroc+nBu0bdRqhUxeMeZyGAzjHt3vuwYMlJsxqQkdWfjOHiGkueWl/F1kV1RLTjO/xX8L0yGNcDB4NgviyUSqOv0c+PU4d3NXS2QCVKep238hCADq7N/1jW1vvw7z4DoaHTclOvIMaOhV+wCwjTUF6s8yOoV0DQmvw9fj/xVCT8yS7VL3bvrbQiZfH8TYPrssGqp8nfUJ8mjtZCW0MQbs9jM5azO5qRChbfGIa90zZL+h8jZThuCl0WtfeIDqngmeFounBBBw7kAx+oPYwCvxRck+TVEKUR0ExlTpTmav0yBopfuozpqtzbAGEhijgLzlLys1EBXC9Dot3KP3IFL6l5n4ntmCH4EnPpDpL0+vpUUQXKtXbsxBae30L79ru3d9R8fMwNbDSDo6IeTLrT/qXy6yWRxHgoIp8fCTJ4UWFQ9IV5PIr6CEb/n304uMY0DROvJk0+k/LT1EHDuSu9S3Zw9oqGGfZgpF8ebJWngs6Rbeic83mSaUe65h2x5yH67J8wzs15lz4XV5mdGfX7iGlYWeVEx3qmSDEAgrzqgykB4w/BVi1Jmr4/mTso+ZRUAjeHoi/yP1hiT4dCwGZDvCx3PbdP42027GJMLQTwrmbw2d+ObZYqqCmaP0axKrd1cv9rEdh8eE="
