language: java

deploy:
  provider: releases
    secure: FgLzkb4joN3Wt7xfApBiPHFvpXp7LpxdJYjzkxMwLafvNmF5Gu1yVzaP5Tx/X0Jf31EZTvIVHX92xpNmtUFCbHXcTZ1NAuDioODsQ5zp4OaX3QhY+GrqK6jwGwmeS715PDm914dp7R785ojPGgxW+5CY+yFi2xmMaF4ChpgTOwG8dFS8RiK7kScRWvwfPW5E91XiHXCcZsLEDI7/rG6UF9K9QpLvSN2KmI59MaFDOMiPNQTo4gGD0/ProYWKQ5jUHCrNpMaj9q/GWsQwLnh9Xbxo/X7c5EDJTmVvqf61iWGSOgsWncPMkL05WQNRFLVL257/ORCHp+J6lJbZ23aNoN+kUfc+H66jG/yEeoUkJC7N4ezHTAW/JM8fNhoauau8OpnNfqHbHPsBn0XLCdSkOHSsb/jh1Wyk7rRP39fuQFNBUWiAvHPCVd4P0gybzCl237mQyH5QJvsFxwfAvD7GYugeybHeQb3+50/YPBa03+nZIL+b/UT52dvvBDa6Kz2lbOieiFH//U6wRU9hW8yZayUjj1WUBwyKJ/cBVMWGNYqMn8p3FAHNYOtwxQ4x+w/T/22ZBt4D0mqIprk9MxEV3I+InrJYH1JRuzKETmvz22/reuey0sYCSCD8f3gGbwoebUVSFxroTHdqHcBB2l4RAV39/MfbdGLDlskE+dF2xwE=
  file:
  - com.pastdev.liferay.scripting-api/target/com.pastdev.liferay.scripting-api.jar
  - com.pastdev.liferay.scripting-service/target/com.pastdev.liferay.scripting-service.jar
  skip_cleanup: true
  on:
    tags: true