language: java

before_install:
- export RELEASE_VERSION=$(mvn org.codehaus.mojo:exec-maven-plugin:1.3.1:exec -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive -Drevision=".$TRAVIS_BUILD_NUMBER" -B)

install:
- echo "Building [$RELEASE_VERSION]"
- mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -V -Drevision=$TRAVIS_BUILD_NUMBER -B

script:
- echo "Testing [$RELASE_VERSION]"
- mvn test -Drevision=$TRAVIS_BUILD_NUMBER -B

before_deploy:
- echo "Releasing [$RELASE_VERSION]"
- openssl aes-256-cbc -K $encrypted_8d05669b0f5a_key -iv $encrypted_8d05669b0f5a_iv -in .travis.codesigning.asc.enc -out .travis.codesigning.asc -d
- gpg --fast-import .travis.codesigning.asc
- mvn deploy -P release -DskipTests=true --settings .travis.settings.xml -Drevision=$TRAVIS_BUILD_NUMBER -B
- git config --local user.name "Lucas Theisen"
- git config --local user.email "lucastheisen@pastdev.com"
- git tag -a -m "v$RELEASE_VERSION" $RELEASE_VERSION

deploy:
  provider: releases
  api_key:
    secure: FgLzkb4joN3Wt7xfApBiPHFvpXp7LpxdJYjzkxMwLafvNmF5Gu1yVzaP5Tx/X0Jf31EZTvIVHX92xpNmtUFCbHXcTZ1NAuDioODsQ5zp4OaX3QhY+GrqK6jwGwmeS715PDm914dp7R785ojPGgxW+5CY+yFi2xmMaF4ChpgTOwG8dFS8RiK7kScRWvwfPW5E91XiHXCcZsLEDI7/rG6UF9K9QpLvSN2KmI59MaFDOMiPNQTo4gGD0/ProYWKQ5jUHCrNpMaj9q/GWsQwLnh9Xbxo/X7c5EDJTmVvqf61iWGSOgsWncPMkL05WQNRFLVL257/ORCHp+J6lJbZ23aNoN+kUfc+H66jG/yEeoUkJC7N4ezHTAW/JM8fNhoauau8OpnNfqHbHPsBn0XLCdSkOHSsb/jh1Wyk7rRP39fuQFNBUWiAvHPCVd4P0gybzCl237mQyH5QJvsFxwfAvD7GYugeybHeQb3+50/YPBa03+nZIL+b/UT52dvvBDa6Kz2lbOieiFH//U6wRU9hW8yZayUjj1WUBwyKJ/cBVMWGNYqMn8p3FAHNYOtwxQ4x+w/T/22ZBt4D0mqIprk9MxEV3I+InrJYH1JRuzKETmvz22/reuey0sYCSCD8f3gGbwoebUVSFxroTHdqHcBB2l4RAV39/MfbdGLDlskE+dF2xwE=
  on:
    branch: master
    tags: false

# travis encrypt MAVEN_REPO_PASSWORD='REDACTED'
# travis encrypt MAVEN_REPO_USERNAME='REDACTED'
# travis encrypt MAVEN_GPG_KEYNAME='REDACTED'
# travis encrypt MAVEN_GPG_PASSPHRASE='REDACTED'
env:
  global:
    - secure: "POh6DD8DyOjxr3q1w1MFWB4VfZuygvkdMEqJMffEiGBeoIQiyWiJLgRNhcykcHvOYhzBkYwWskJBdUdxSpiJGswC5vOXYWdgMwwKoBV8ejsMbFNGy4baHMfp4N4qZ06I8a6AxMu6JfEW9LN5Iv5OnbRKWFTMj8vWoy5tOuzsauG9i4LgSYOckz8AxAUaalVqsr5DAw4C49YbZbloaoDpo7J3yTdzoGjZntRe0z70jMY4SwSibH9TYR+qXRa0SCArNERLLUkK8ZMISv+cWFC6Non/zZLYWNHCXIo7DMDfYbXrVFanghpa4JSPXzYO8ez7wmD8bRhGIZommrFfHTeueqaoRMK8CG+JkB18KXr0yfsIQbtc84g797oRXRoeIDtOkqGgxIW+xvoXaXdHXVuZsfGJ/unchjtUdsQjkQmcOralRLbpQdfzeTZY4ePdgyqMyCaWOV4yFE+b0t+s+G/V/Whbiq5CbwDZi/oL3YLcfIpHeU42i4OS8PdLSnEffbBxhsBbhwqff8HhUO0qshyOzSMmW6BAIsmecPpMA7coKyPQOZv+6AwlrLTpl4jg8W8aszODFd5w2y+rVCx//RLdwsHOOn9P67g7NCR1GVADgwanJ5tF98HTxSXoAxxZeC09MQyni6MHo3z+WQ7a7p2jn6xj4keW0rx4Q9Z2IDLqmog="
    - secure: "EAJQckdW7/fQ55NTyy+A9VGtv6ChBm7oX3sMrSQv7U4nrG3TtfMR3YOYWVf0lCYpUykzX8CDt8ZCGfWqQuCxsdbw0vy3PANHNmKw40Nj6TlcM1yF1W5Y5wSv/1aP/VmdtnI7uH9cApYDyMR5HePHxfQ/rkBRmcVq2mqglJ0hDoM1Sy7TM8j2SUQgtcvHS14iLmr200UGSpRJ+sdHqu6nMJifAF3I6xOYS+cRji86StfcYsg7a6mK7C0wOXIqZolSlJvPAARgRVXUIduzYdDvYFiVSJ0DVA0KKSzeYcwn6Mk4leqzowexMl9pM5BA1ODkyaVrIkRMoVGqg9nEl5p3NQrKNm+BrEhtv81KcSENGKQwyPz00Yryq/27soziNllukSppX0ISwWfAHH/hTRjmhnmsyLvMORYlaAARLvbJASxfa2cenjuY04kHLzE1v4y4mvYTl2FKrSRLN1hDkfFlGj0pVZBAasDpKRnvkgdjR8LM/eXnpUdXdvAV8PM9QqTDOyDVYg97A/Ad8+HTLaQsDe5QWpHllgykrY59NFImHO67sYRCCKBsZ2Airz6C1KGqf8geaJOGnL8hvLn6cNZuCfh57/ocLwBvSeIr7RJ63sd2mcIGeEXOnZcgUlG7Fj+u+S6sn4kyDuZCmwJcTtkGBhpkKRE7FOg9X3p8JR0jZoY="
    - secure: "Sg3QR2x/vR/7YRrLwh4V+ecuDPt4Gd/+Cvz8ElbnUbX0akLJ3uyfjN44VcRcogog0sUhKttSrcOeY2696lmSchf5zRq6BIL+wvLFLWdIzJ0E/Cq8LT4JaFMRugcbh5yPecclqT80CaUVNAQdnp6K98b9nkVCDvyO1HkYmo3foT87xjQ89Duk3WKtEyK7c3RbvtDWTeskiRmomdDqG/eQ/aH5z/ABj9naM7pJjHbi1hKeK5RpZMICiOUdJw2gC9UZQQ8rnB7xhyimU+8Dg+kl8XHAYoK3pQEpHht2oJtySMONMb9pbIsHNRAEQu5AYPCAqDBdsRy844rJYgG8AnTrppFkiLnLpNFHPG+rDZUIM+mNMYtG5SBRyRJFCwEBFEpiZP2wEj57v7LvgTqFbZJJwcJ50jIJgeBBj1d8L33ers7x29n3nmTSLFdsdbN0RUXx+jQkEM7/f2WezbcYyw3sMKBxW5E+onwNyf7mDblj5tmqXpkgT+5QF67QmCn8sdGWqVPJKyNNb/wj4fLII/zxPucEOqZjKWbU+ALiappkMu93sTf6itm/wotrI+gAF8PVeRbVgYjzy6t0khhknq5zJQBQeolRF44isikmgHyUI0ZKPQn+KwcX/gjBbc5QJpvRGJqRNr56ux8vR5o8cATevYJfeHFEtU2u27aQPZH8Csw="
    - secure: "B/zHGkOtVveqZkCpqqOuIDvbvvOMkziBzrzCU/tRndBS4GjyK5+sV2rimHqSKy0mjonkrp5cPEYDE8LOTfkRFnimfMUSM7hoQRfHdgHEGDN8VT0HpZNRwLak6E2RIdfFOE73H7EmWUY4kK2fwXbVj0v2qzEBN5O/wd3G0eAzt62v15FMDU0ALnVjh2c68D0W0vfP+k08DukW64bSDYJow4eBvgsd7P7hxjvp/y6slCVHMcBjBT/VT35vdLC0jL0D9FPYB/E2n5pRiyuQ2qkk8iVSTxeogN71u6iCB+VVjCbqC/489LB3/1HhSsatJhvTIh6wA+J5iJC/nzx6AxCgpEp+543LU+NwMt/boZcxZZaOlZ9UdWv6RzOiC+ZybGAs9tjXPFr0fZmf+CA/KemuXN3G+9FGmJNGB1zGkfiZ8C4TFCvJW4QZUsgycbn102eVYVDgIGyBaKgSukYMHu15yHttlclC0J8PsDdas1QCzh41eLWeo012TJbkd7yyOr7zPxRAj4B5S6EyXmaqh3jvkiVo7IsWvkKGamAlVe/RiF6SB/rS5De1NO7OKcPmsLgPdUetL4NRS8n4u44W3XyVkerFyRoLOgy5pWscQC8MLtzUChNZyha4zmrF+R4uEc8JY5BPr3BE6+K4w7+WOzEjzWDqp+wSABGUB96ogc4qpvI="

